// This file is automatically generated by the Firebase setup process.
// Do not modify this file manually.

export const firebaseConfig = {
  apiKey: "AIzaSyDdxqpBRVLlBQ_qVAJ7vqZopy-ynPHEUBo",
  authDomain: "kyozo-7f801.firebaseapp.com",
  projectId: "kyozo-7f801",
  storageBucket: "kyozo-7f801.appspot.com",
  messagingSenderId: "782676535922",
  appId: "1:782676535922:web:152538c6412b7a97c23f13",
  measurementId: "G-93V44B5N0G"
};
