// This file is automatically generated by the Firebase setup process.
// Do not modify this file manually.

export const firebaseConfig = {
  apiKey: "AIzaSyALpnr-pNEyAQUgYBgVwfDIguJ_lu7_KQY",
  authDomain: "kyozo-prod.firebaseapp.com",
  projectId: "kyozo-prod",
  storageBucket: "kyozo-prod.appspot.com",
  messagingSenderId: "480316724826",
  appId: "1:480316724826:web:152538c6412b7a97c23f13",
  measurementId: "G-93V44B5N0G"
};
