// This file is automatically generated by the Firebase setup process.
// Do not modify this file manually.

export const oldFirebaseConfig = {
  apiKey: "AIzaSyBq19WxHe0bZDY2JVzIyrb9dH-nU4Rrn9E",
  authDomain: "kyozo-pro-webflow-fb6c.firebaseapp.com",
  projectId: "kyozo-pro-webflow-fb6cc",
  storageBucket: "kyozo-pro-webflow-fb6c.appspot.com",
  messagingSenderId: "325455673540",
  appId: "1:325455673540:web:9e12d352c3855a8235e7c8",
  measurementId: "G-93V44B5N0G"
};
